# Generated by Django 4.0.2 on 2022-02-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_new_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_User',
            new_name='Patient',
        ),
    ]
