# Generated by Django 4.0.2 on 2022-02-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_new_user_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
