# Generated by Django 4.0.2 on 2022-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('trans', 'Prefer not to say')], max_length=200),
        ),
    ]
