# Generated by Django 4.0.2 on 2022-02-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_appointment_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
