# Generated by Django 4.2.6 on 2023-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_auto_20200828_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingaddress",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
