# Generated by Django 4.2.6 on 2023-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_order_postorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
