# Generated by Django 4.2.6 on 2023-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0043_auto_20210403_0752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medcat",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
